### ISSUE TITLE
`*const char` should be translated `*uint`

### ISSUE THREAD

**Issue by lassade** [Cysharp/csbindgen#16]
Hi, thanks for this awesome crate :)

I think `*const char` should be translate to `*const uint`.

- In the `0.1.2` I was getting `*char` but I don't think this is acurate because `sizeof(char) == 2` so the aligment might be also off
- In the `1.4.0` I'm getting a `*@char` not sure what is happening

**Comment by lassade** [comment]
`*const u32` is also been translated to `*uint` instead of `*nuint` is that correct?

**Comment by neuecc** [comment]
char is not FFI-Safe, therefore, we do not provide the mapping.
When do you use char?

Since cbindgen also maps to uint32, I think uint is fine.
https://github.com/eqrion/cbindgen/issues/814

**Comment by lassade** [comment]
I changed everything to u32, thanks!
