### ISSUE TITLE
Call unity function and return unity object?

### ISSUE THREAD

**Issue by oovm** [Cysharp/csbindgen#21]
Is it possible to read the data of unity in rust, and after calculation, return a unity object?

For example, read `Vector3` and return `List<Vector3>` in rust side?

**Comment by neuecc** [comment]
`List<T>` can be easily shared with Rust if given the same memory structure, that is, a structure that can obtain the length and pointer.
For example, you can use a helper like this to convert it to `Span<Vector3>` and pass the `Vector3*` and length:
https://github.com/Cysharp/MemoryPack/blob/main/src/MemoryPack.Core/Internal/CollectionsMarshalEx.cs

**Comment by oovm** [comment]
Thanks, I've got the key idea.
