### ISSUE TITLE
About document generation

### ISSUE THREAD

**Issue by oovm** [Cysharp/csbindgen#25]
Existing documentation generation seems to simply add `summary`?

It does not convert rustdoc markdown syntax to C# doc syntax.

How about remove the summary, and I can directly write xml-style C# documents?

**Comment by neuecc** [comment]
I understand that it is quite inadequate, since per argument COMMENT is not supported either.
https://github.com/rust-lang/rust/issues/57525
However, I am not willing to add any special mechanism.

**Comment by jakob-ledermann** [comment]
How about adding the same mechanism as `bindgen` did with `parse_callbacks` and `ParseCallbacks::process_comment`?
That would allow users to write their own document converters.

**Comment by neuecc** [comment]
I feel like it might not be too bad, but since I can't quite picture it, the status is more like "I might do it someday.
