### ISSUE TITLE
C# DLL's Cannot Be Found With Readme Example

### ISSUE THREAD

**Issue by NicholasMaselli** [Cysharp/csbindgen#28]
Hello! I just found the library today and I've been playing around with it. But I may have found a few issues with the readme example (I could also be doing something very silly but I've looked around for a while)

I have a very simple program.cs file:

```
using CsBindgen;

Console.WriteLine(NativeMethods.my_add(1, 2));
```

I have a build.rs that looks like this:

```
fn main() {
    csbindgen::Builder::default()
        .input_extern_file("src/lib.rs")
        .csharp_dll_name("nativelib")
        .generate_csharp_file("./dotnet/NativeMethods.g.cs")
        .unwrap();
}
```

with a src/lib.rs that looks like this:

```
// lib.rs, simple FFI code
#[no_mangle]
pub extern "C" fn my_add(x: i32, y: i32) -> i32 {
    x + y
}
```

And a Cargo.toml file that looks like this:

```
[package]
name = "test-blob"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
csbindgen = "1.7.2"
```

When I run the code I get the C# File NativeMethods.g.cs that looks like this:

```
// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;

namespace CsBindgen
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "nativelib";

        [DllImport(__DllName, EntryPoint = "my_add", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int my_add(int x, int y);
    }
}
    
```

I've removed the "unsafe" keyword and change "internal" to "public" however, when I run ```dotnet run```

I get this error

```
Hello, World!
Unhandled exception. System.DllNotFoundException: Unable to load DLL 'nativelib' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at CsBindgen.NativeMethods.my_add(Int32 x, Int32 y)
   at Program.<Main>$(String[] args) in Program.cs:line 7
```

I've tried several methods of fixing this but it looks like the target folder from ``cargo build``` did not build the dll. 

Do you know a way to fix this? This seems like a very silly error that I am making but I cannot seem to figure it out

**Comment by neuecc** [comment]
similar issue in https://github.com/Cysharp/csbindgen/pull/27 ?
andalso, csbindgen does not put dll file to your C# project.
when you run `cargo build`, maybe found `target/debug/nativelib.dll` in directory.
please copy and put your self.

**Comment by NicholasMaselli** [comment]
Alright!

I added 

[lib]
crate-type = ["cdylib"]

to the Cargo.toml and it gave me a dll with the name of the project that worked thank you! I will make a PR to add to the readme =)
