### ISSUE TITLE
Support generating bindings from dependent crates

### ISSUE THREAD

**Issue by yanchith** [Cysharp/csbindgen#30]
Can csbindgen look at a crates's dependencies when generating bindings? Let's imagine

Crate `dll`:

```rust
pub use api_types::Vec2;

fn function(x: *const Vec2) {}
```

Crate `types`:

```rust
#[repr(C)]
pub struct Vec2 {
    pub x: f32,
    pub y: f32,
}
```

Currently it looks like it doesn't search dependencies for types to output. If we run csbindgen in `dll/build.rs`, it won't include types defined in `types`.

**Comment by neuecc** [comment]
We do not plan to add dependency analysis currently (or in the future).
Please call `input_bindgen_file` multiple times and manually add the necessary dependency files as needed.

**Comment by yanchith** [comment]
Yeah, thanks. I managed to set up the structure such that it somehow works.

**Comment by pherbel** [comment]
@yanchith Could you please share some sample how you achieved this.

I want to create a C# binding for existing rust lib. I would just use as a dependecy and reference it for build.

@neuecc  Do you have any exmaple for similar?

I appreciate you help.

(Sorry if it is stupid question. I'm not familliar with rust ecosystem.)

**Comment by yanchith** [comment]
@pherbel I literally just applied the suggestion, and called `input_bindgen_file` multiple times on multiple files.

> I want to create a C# binding for existing rust lib. I would just use as a dependecy and reference it for build.

Unless the library was specifically structured beforehand to gel well with bindings generators, you might run into trouble. I can't share the codebase I am working on, but my loose inspiration was the wgpu crate from around 3-4 years ago. They used to have (maybe still do, IDK) a very clean separation of what is visible from C and what isn't. You can still see parts of it in https://github.com/gfx-rs/wgpu/blob/trunk/wgpu-types/src/lib.rs, where they define the C-visible types.
