### ISSUE TITLE
Support constants?

### ISSUE THREAD

**Issue by yanchith** [Cysharp/csbindgen#31]
If there is a constant in the Rust file, it is not does not appear in the generated bindings. 

```rust
pub const THINGY_CREATE_FLAGS__OPTIMIZE: u32 = 1 << 0;
```

For instance cbindgen makes this a `#define`, if you target C.
```C
#define THINGY_CREATE_FLAGS__OPTIMIZE (1 << 0)
```

**Comment by neuecc** [comment]
Parameter that are not used in method signature will not be generated, and wouldn't it be difficult to include constants in the signature?

**Comment by yanchith** [comment]
Not sure I understand your comment, but I'll try elaborating.

The usecase is not to directly use the constants in a method signature, but to provide something to build the method parameter with. E.g. I can have a function:

```rust
#[no_mangle]
pub extern "C" fn thingy_create(thingy_ptr: *mut Thingy, flags: u32) {}
```

Which I can then call with the constants that would be also generated with the header.

```C#
Thingy thingy;
Bindings.thingy_create(&thingy, Bindings.THINGY_CREATE_FLAGS__OPTIMIZE);
```

At the moment, I have worked around this with functions. I have:

```rust
#[no_mangle]
pub extern "C" fn thingy_create_flags__optimize() -> u32 { 1 << 0 }
```

.. but I'd rather not have to do this, especially because C# bindings are not the only ones I am generating, and now I have to have separate workarounds for cbindgen and csbindgen.

**Comment by neuecc** [comment]
Ver.1.7.4 supports generate const option.
