### ISSUE TITLE
Support configurable calling convention or infer it from function declaration?

### ISSUE THREAD

**Issue by yanchith** [Cysharp/csbindgen#32]
Sorry for the messy text. I am trying to understand the historical layers here. Therefore, this is 60% question, 40% feature request.

I'll start with the fact that I am a bit confused about what calling convention actually is the default on which platform.

The Rust reference says something about the default here: https://doc.rust-lang.org/reference/items/external-blocks.html#abi. It says that `cdecl` is only the default on x86_32, but on x86_64 the default is `win64`, but on the forums it is said that `extern "C"` is whatever LLVM considers to be the default. LLVM docs say that the default "C" calling convention is indeed `cdecl`. https://llvm.org/doxygen/namespacellvm_1_1CallingConv.html

C#'s `CallingConvention` enum doesn't even have a field for `win64`, so I guess that calling convention isn't actually used much?

The question: Is `cdecl` really the default everywhere?

---

This said, it would be useful, if we could configure the calling convention for the generated bindings. What if we do `extern "stdcall" fn` in Rust? Currently, csbindgen doesn't pick it up.

**Comment by neuecc** [comment]
When calling the Win32API, we use stdcall. However, for purposes like csbindgen, there's probably no need to deliberately use it. 
I believe cdecl should suffice.
