### ISSUE TITLE
Is there an example to interoperate cross async boundary?

### ISSUE THREAD

**Issue by tisonkun** [Cysharp/csbindgen#36]
That said, how can I integrate Rust's `async`/`await` with C#'s `async`/`await`.

**Comment by neuecc** [comment]
can not.
It is not part of the interop specification.
You may convert it to a callback and pass it on to C#.

**Comment by tisonkun** [comment]
@neuecc Then what is the standard C# concurrent unit (pattern) I can follow?

For comparing, I interoperate Rust's async/await with Java's CompletableFuture in OpenDAL Java binding in the following way:

* Java side https://github.com/apache/incubator-opendal/blob/ab9f0a844076ece16f31a023e713f0dfc48262d5/bindings/java/src/main/java/org/apache/opendal/Operator.java#L34-L99
* Rust side 
  * https://github.com/apache/incubator-opendal/blob/ab9f0a844076ece16f31a023e713f0dfc48262d5/bindings/java/src/operator.rs
  * https://github.com/apache/incubator-opendal/blob/ab9f0a844076ece16f31a023e713f0dfc48262d5/bindings/java/src/lib.rs#L49-L66

I'm looking for the counterpart for C# and here comes the original issue.

**Comment by neuecc** [comment]
The equivalent of CompletableFuture is TaskCompletionSource, but that can't be binding JNI.
