### ISSUE TITLE
C# Action

### ISSUE THREAD

**Issue by Odonno** [Cysharp/csbindgen#43]
Hi,

We currently have to write static callback to get a future response from a Rust function. Example:

```cs
unsafe
{
    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    static void MyCallback()
    {
        // Ok callback
    }

    [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]
    static void MyErrorCallback(byte* cString)
    {
        // Error callback
    }

      NativeMethods.fn(
          &MyCallback,
          &MyErrorCallback
      );
}
```

Would it be possible to use create `Action` this way so that we can stay in the same context:

```cs
unsafe
{
    var callback = () => 
    {
        // Ok callback
    };

    var errorCallback = (byte* cString) =>
    {
        // Error callback
    };

    NativeMethods.fn(
        &callback,
        &errorCallback
    );
}
```

**Comment by startewho** [comment]
it you use the function pointer ,it must be static.

**Comment by Odonno** [comment]
Hi, thank you for your answer and thank you for this library BTW.

However, your answer is not explicit. So, I should conclude that there is no way to avoid `static`? If so, I should find a workaround.

**Comment by Skgland** [comment]
@Odonno If its still of interest I created a demonstration project for a workaround at <https://github.com/Skgland/calling-c-sharp-actions-from-rust>

**Comment by Odonno** [comment]
> @Odonno If its still of interest I created a demonstration project for a workaround at https://github.com/Skgland/calling-c-sharp-actions-from-rust

Yes. That was one of my idea. That looks really simple. Thank you very much for sharing this.
