### ISSUE TITLE
Add an option to rename structs

### ISSUE THREAD

**Issue by BenoitZugmeyer** [Cysharp/csbindgen#56]
Thanks for your cool project!

I was wondering if `csbindgen` could have a way to rename struct/enums/constants, similarly to [cbindgen with `[export.rename]`](https://github.com/mozilla/cbindgen/blob/master/docs.md)?

<details>
<summary>Context</summary>
 

I am creating a Rust library that will be used by a C# program. Most of my library is implemented without FFI in mind, and sometimes I need to convert structs from my library to semantically equivalent data structures that I can share through FFI. For example:

```rust
struct Configuration {
  version: String
}

// ffi equivalent:
#[repr(C)]
struct Configuration {
  version: *const c_char
}
```

This works well, but I have a naming clash: both structures are called `Configuration`!

Ideally, I would like to keep using the original name in my lib, and use another name for the FFI version, for example:

```rust
struct Configuration {
  version: String
}

// ffi equivalent:
#[repr(C)]
struct FfiConfiguration {
  version: *const c_char
}
```

But when generating the C# file, I don't want those `Ffi` prefixes, I'd prefer to expose the original name.
</details>

This could maybe be implemented as a new `csbindgen::Builder` method, like so:

```rust
csbindgen::Builder::default()
  .rename("FfiConfiguration", "Configuration")
```

**Comment by neuecc** [comment]
Thanks, that's a good suggestion.
I will try to pass the FUNCTION for renaming.

**Comment by neuecc** [comment]
added in `1.9.0`.
