### ISSUE TITLE
How to generate struct when i not have a .rs file?

### ISSUE THREAD

**Issue by MoutainPL** [Cysharp/csbindgen#59]
I  defined a struct in a crate:
```rust
   #[repr(C)]
   pub struct ByteVecPtr {
     pub ptr: *const u8,
     pub len: usize,
   }
```
How to generate  this struct to csharp when i dependency the struct . I can't find the .rs file when dependence on crate.io.
```rust
   #[no_mangle]
    pub extern "C" fn ads_read_motor_para_l(byte_vec_ptr:ByteVecPtr) -> bool {
         return true;
     }
```

**Comment by hadashiA** [comment]
Good suggestion.
However, it seems difficult to include this feature immediately at present.

Apparently [mozilla/cbindgen](https://github.com/mozilla/cbindgen) has the ability to parse dependencies. 
However, they have built a large mechanism such as parsing Cargo.toml/Cargo.lock and downloading source code by compiling dependencies using the cargo command line tool. (https://github.com/mozilla/cbindgen/blob/master/src/bindgen/cargo/cargo_expand.rs)

If cago provided an API to do this, it would be easier to implement. But if not, it's a bit of a big deal.
