### ISSUE TITLE
Can it be used for c# to Rust?

### ISSUE THREAD

**Issue by asmitaj08** [Cysharp/csbindgen#64]
Hi,
Can it be used for using c# within Rust (i.e. c# to rust)?

**Comment by snaulX** [comment]
No. How do you imagine it?

**Comment by asmitaj08** [comment]
I meant if we can do any changes so that vice versa could be possible. Apologies for the dumb question.

**Comment by hadashiA** [comment]
Hmmm. Maybe csbindgen doesn't meet this title request.

**Comment by asmitaj08** [comment]
Yes, I was a bit confused by this example. Thought we can use c# codes within rust using this approach. Maybe not the direct generation of rust from c#, but could meet the purpose, if we want to use any c# code within Rust based framework. 
<img width="685" alt="Screenshot 2024-01-05 at 10 46 24 AM" src="https://github.com/Cysharp/csbindgen/assets/57127733/5379fbac-0ee9-4939-8ed5-88408fb83af9">

**Comment by kaesaecracker** [comment]
@asmitaj08 I do not know if you sill care, and I hope I do not break a rule by resurrecting this thread, but you can actually do what you described above.

1. start a .NET app
2. call native methods to initialize function pointers
3. call the rust entry point
4. call the function pointers from native code

That way you can build objects that live in native code and get wrapped in C#, or objects living in C# that get called from native code. It is soooo much boilerplate, but the resulting API is decent and safe-ish.

Two examples for that can be found in my public repos:
- Demo project, native calls C#: https://github.com/kaesaecracker/CSharpNativeInterop
- A rust library with C# bindings, C# calls native https://github.com/cccb/servicepoint/tree/main/crates/servicepoint_binding_cs
