### ISSUE TITLE
Build using input_bindgen_file() isn't generating FFI code

### ISSUE THREAD

**Issue by TMason11095** [Cysharp/csbindgen#70]
I don't use Rust, so I'm not sure if I'm just setting up the files incorrectly, but I'm trying to take [existing Rust code](https://github.com/ankitects/anki/tree/main/rslib) and call the functions from within C#.

I setup a submodule for the existing repo and then made a rslib-bridge folder to hold the csbindgen code.
Here are my files:

Cargo.toml
```
[package]
name = "rslib-bridge"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]

[build-dependencies]
csbindgen = "1.8.0"
```

build.rs
```
fn main() {
    csbindgen::Builder::default()
        .input_bindgen_file("../anki/rslib/src/decks/service.rs")
        .rust_file_header("use super::service::*;")
        .csharp_entry_point_prefix("csbindgen_")
        .csharp_dll_name("service")
        .generate_to_file("service_ffi.rs", "../dotnet/NativeMethods.service.g.cs")
        .unwrap();
}
```

[This](https://github.com/ankitects/anki/blob/main/rslib/src/decks/service.rs) is the existing Rust file that I'm trying to generate from.
When I run `cargo build`, I get the generated service_ffi.rs file, but it doesn't contain any of the function calls.

service_ffi.rs
```
/* automatically generated by csbindgen */

#[allow(unused)]
use ::std::os::raw::*;

use super::service::*;


    
```

I thought maybe it was because the service.rs file I'm pulling from uses `impl` and has all the functions nested in it, instead of having them at the base level. So I deleted the generated files and tried again but this time using the default generated lib.rs file (with the test deleted) and got the same result.

src/lib.rs
```
pub fn add(left: usize, right: usize) -> usize {
    left + right
}
```

build.rs
```
fn main() {
    csbindgen::Builder::default()
        .input_bindgen_file("src/lib.rs")
        .rust_file_header("use super::service::*;")
        .csharp_entry_point_prefix("csbindgen_")
        .csharp_dll_name("service")
        .generate_to_file("service_ffi.rs", "../dotnet/NativeMethods.service.g.cs")
        .unwrap();
}
```

**Comment by TMason11095** [comment]
Sorry maybe I misinterpreted the [Rust to C#](https://github.com/Cysharp/csbindgen#rust-to-c) and [C (to Rust) to C#](https://github.com/Cysharp/csbindgen#c-to-rust-to-c) code examples, but I thought the `.input_extern_file()` was the one that required the Rust file to have `#[no_mangle]` and `extern "C"` on all the functions, not `.input_bindgen_file()`?

The `.input_extern_file()` example shows an input Rust file of:
```
// lib.rs, simple FFI code
#[no_mangle]
pub extern "C" fn my_add(x: i32, y: i32) -> i32 {
    x + y
}
```
And the `.input_bindgen_file()` with `.generate_to_file()` example doesn't show the in-between `lz4.rs` file, but it does show the final `lz4_ffi.rs` file:
```
// lz4_ffi.rs

#[allow(unused)]
use ::std::os::raw::*;

use super::lz4::*;

#[no_mangle]
pub unsafe extern "C" fn csbindgen_LZ4_compress_default(src: *const c_char, dst: *mut c_char, srcSize:  c_int, dstCapacity:  c_int) ->  c_int
{
    LZ4_compress_default(src, dst, srcSize, dstCapacity)
}
```
Since the input for `.input_extern_file()` and the output for `.input_bindgen_file()` with `.generate_to_file()` both seemed similar, I figured `.input_bindgen_file()` was just taking a standard Rust file that was generated from C. If that's not the case and the `.input_bindgen_file()` requires `#[no_mangle]` and `extern "C"`, then is it just taking the file, adding the
```
#[allow(unused)]
use ::std::os::raw::*;

use super::lz4::*;
```
to the top and updating the function arguments to be `c_`?

In the [emitter.rs](https://github.com/Cysharp/csbindgen/blob/main/csbindgen/src/emitter.rs) file, I see
```
        let template = format!(
            "
#[no_mangle]
pub unsafe extern \"C\" fn {method_prefix}{method_name}(
{parameters}
){return_line}
{{
    {method_type_path2}{method_name}(
{parameter_only_names}
    )
}}
"
        );
```
which looks like what I'm trying to do (add `#[no_mangle]` and `extern "C"` to existing Rust code), but I can't really follow what exactly is required to trigger it in [lib.rs](https://github.com/Cysharp/csbindgen/blob/9fff4241e5f74ec431fe57c979ec0067207f642a/csbindgen/src/lib.rs)'s `generate()` function. My best guess would be that it triggers when you use `.input_bindgen_file()`, but not `.input_extern_file()`, which is what I did in my `build.rs` file.

**Comment by hadashiA** [comment]
https://github.com/Cysharp/csbindgen/issues/70#issuecomment-1883531368 As noted in the comments here, to be eligible for csbindgen, the following conditions must be met:

- pattern 1 
  - An implementation of a function in rust with `extern "C"`.
    - Note: 
      - The Strictly speaking, the extern "{ABI}" part is supposed to have options other than "C", so it is the presence or absence of `extern` that is checked mechanically.
  - And if `#[no_mangle]` or `#[export_name = "."] ` attribute.
- pattern 2 `extern "..." { ... }` block containing signature declarations for functions in another language than Rust.
  - This is a only function declaration for FFI from Rust to C etc. So there is no implementation.

Accordingly,
`.input_extern_file` is for 1.
`.input_bindgen_file` is for 2. 

The reason for the `input_bindgen_file` name is that the 2 signature is typically the file created by Rust's [bindgen](https://github.com/rust-lang/rust-bindgen).

If the implementation of the code you want to call is Rust, use method 1. If your code is in C, etc., would you consider method 2?

**Comment by TMason11095** [comment]
Ah ok. I understand now. Thank you for the explanation.

Would it be possible to implement a function that takes a standard Rust file and generates another file that calls that function, but with `#[no_mangle]` and `extern "C"`?

So it takes:
```
pub fn add(left: usize, right: usize) -> usize {
    left + right
}
```

And outputs:
```
use hello::add;

#[no_mangle]
pub unsafe extern "C" fn unsafe_add(left: usize, right: usize) -> usize {
    add(left, right)
}
```
With:
```
[dependencies]
hello = { path = "../hello" }
```
(where `../hello` is the path to the input file) added to the Cargo.toml file.

Or would that be more involved and require something like a proto file?

**Comment by sappho192** [comment]
Hello, I'm new to Rust and also having problem generating FFI code (NativeMethods.cs)
However dll file is successfully generated and I could call them by manually writing `NativeMethods.cs` file.

Here are the steps what I did:

1. In Windows, I made a fresh new library with `cargo new --lib mylib`
2. I modified `lib.rs` like below:
```Rust
// lib.rs, simple FFI code
#[no_mangle]
pub extern "C" fn my_add(x: i32, y: i32) -> i32 {
    x + y
}
```
3. Created a `build.rs` like below:
```Rust
fn main() {
    csbindgen::Builder::default()
        .input_extern_file("lib.rs")
        .csharp_dll_name("mylib")
        .csharp_class_name("NativeMethods")
        .generate_csharp_file("./NativeMethods.cs")
        .unwrap();
}
```
4. Add `crate-type` and `build-dependencies` stuff to `cargo.toml`:
```
[package]
name = "mylib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]

[build-dependencies]
csbindgen = "1.9.0"
```
5. Run `cargo build` in the project directory and got the artifacts in the `target` directory like this:
![image](https://github.com/Cysharp/csbindgen/assets/7788738/593ec1f4-b377-464e-964c-cd4d6f3e48f7)

In this step, I couldn't find `NativeMethods.cs` file in anywhere, maybe `generate_csharp_file()` function didn't work correctly with no error...?

6. Create a new C# project and copy the library files generated in step 5.
7. Create a new cs file named `NativeMethods.cs` and filled in like below:
```CSharp
using System.Runtime.InteropServices;

namespace CsBindgen
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "mylib";

        [DllImport(__DllName, EntryPoint = "my_add", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int my_add(int x, int y);
    }
}
```
8. In `Progrm.cs` I called the function like `Console.WriteLine("my_add(1, 2) = {0}", NativeMethods.my_add(1, 2));` and it worked successfully.

So it seems that the library has been generated successfully, but FFI code didn't.

Can anyone give me some advice on this? Thank you in advance.

**Comment by Skgland** [comment]
@sappho192 

I am think the problem is `input_extern_file("lib.rs")` which should be `input_extern_file("src/lib.rs")`instead.

**Comment by sappho192** [comment]
> I am think the problem is `input_extern_file("lib.rs")` which should be `input_extern_file("src/lib.rs")`instead. Also the `build.rs` should be in the project root not in the `src` folder.

Thank you @Skgland ! Now I can get FFI file successfully. 
So the correct file structure should be like this:
![image](https://github.com/Cysharp/csbindgen/assets/7788738/c0a546cf-8d95-41e9-bcb7-2c4c8a51a77a)

@TMason11095 Since it seems that you also want to create C# binding, maybe this can help your problem, too.

**Comment by TMason11095** [comment]
> @TMason11095 Since it seems that you also want to create C# binding, maybe above can help your problem, too. Also don't forget to replace your `.generate_to_file("service_ffi.rs", "../dotnet/NativeMethods.service.g.cs")` to `.generate_csharp_file("NativeMethods.cs")`.

No, unfortunately my issue is that my input Rust file is an existing file that doesn't contain `#[no_mangle]` and `extern "C"` code. So swapping functions calls in the build.rs file doesn't work.

**Comment by hadashiA** [comment]
@TMason11095 describes here should work.
https://github.com/Cysharp/csbindgen/issues/70#issuecomment-1886166730

Rust support the FFI feature. This library simply glues that feature in place.
Let me know if you have any further problems.
