### ISSUE TITLE
Can't get struct bindings unless in the same file

### ISSUE THREAD

**Issue by fakkoweb** [Cysharp/csbindgen#88]
Hi I am going crazy because something that seemed to be working doesn't really work anymore and I have no idea why.

I have a file:
`src/classes/counter.rs`
and its ffi:
`src/ffi/counter_ffi.rs`

I only run csbindgen on **counter_ffi.rs** and until last week it was also generating the empty structs for Counter and Args. But right now I cannot get it. I do not really know why and would need help, since this might be an issue.

Content of counter.rs:
```rust
#[repr(C)]
pub struct Args {
    pub  init: u32,
    pub  by: u32,
}

#[repr(C)]
pub struct Counter {
    val: u32,
    by: u32,
}

impl Counter {
    pub fn new(args: Args) -> Counter {
        Counter{
            val: args.init,
            by: args.by,
        }
    }

    pub fn get(&self) -> u32 {
        self.val
    }

    pub fn incr(&mut self) -> u32 {
        self.val += self.by;
        self.val
    }

    pub fn decr(&mut self) -> u32 {
        self.val -= self.by;
        self.val
    }
}
```

Content of counter_ffi.rs:
```rust
use std::mem::transmute;
use crate::classes::counter::{Args, Counter};

#[no_mangle]
pub extern fn counterCreate(args: Args) -> *mut Counter {
    let _counter = unsafe { transmute(Box::new(Counter::new(args))) };
    _counter
}

#[no_mangle]
pub extern fn counterGetValue(ptr: *mut Counter) -> u32 {
    let mut _counter = unsafe { &mut *ptr };
    _counter.get()
}
```

The resulting .cs file DOES NOT contain the Counter struct, so the code is unusable. But I swear that it worked until now and I got the empty Counter struct there.

CS file:
```cs
    internal static unsafe partial class CounterUnsafeFFI
    {
        [DllImport(__DllName, EntryPoint = "counterCreate", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern Counter* counterCreate(Args args);

        [DllImport(__DllName, EntryPoint = "counterGetValue", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern uint counterGetValue(Counter* ptr);
    }
```

What am I missing? Really the counter_ffi.rs should be in the exact same file of the counter.rs?

**Comment by neuecc** [comment]
I have merged and released some PRs, so if they used to be generated and no longer are, they may have been degraded.
I will look into it.

**Comment by fakkoweb** [comment]
this might be unrelated but when `.csharp_use_function_pointer(false)` does not seem to affect generated Structs.

If you have a:
```
#[repr(C)]
struct PersonCallbacks {
    #[no_mangle]
    pub  get_name: extern "C" fn() -> *const c_char
}
```

with `.csharp_use_function_pointer(true)`, i get a `public delegate* unmanaged[Cdecl]<byte*> get_name` as expected.
with `.csharp_use_function_pointer(false)`, i get a `void*`, while it should probably work as the main static class.

**Comment by neuecc** [comment]
csbindgen does not automatically resolve reference relationships.
Have you added multiple input_files manually?

In ReadMe:

> input_extern_file and input_bindgen_file allow mulitple call, if you need to add dependent struct, use this.

```rust
csbindgen::Builder::default()
    .input_extern_file("src/lib.rs")
    .input_extern_file("src/struct_modules.rs")
    .generate_csharp_file("../dotnet-sandbox/NativeMethods.cs");
```
