### ISSUE TITLE
csbindgen generates unknown type "C"

### ISSUE THREAD

**Issue by kevaundray** [Cysharp/csbindgen#89]
### Version

1.9.2

### Issue 

Given the following Rust enum:

```rust
#[repr(C)]
pub enum CResultStatus {
    Ok,
    Err,
}
```

Version 1.8.0 generated the following csharp enum:

```csharp
    enum CResultStatus : uint
    {
        Ok,
        Err,
    }
```

whereas the new version generates:

```csharp
    enum CResultStatus : C
    {
        Ok,
        Err,
    }
```

dotnet then throws an error due to it not knowing what type `C` is

**Comment by neuecc** [comment]
thanks, I've fixed in 1.9.3.
